#ifndef GLOBALSETTINGS_H
#define GLOBALSETTINGS_H


#define BAUD_RATE 57600

#define PIN_SHUTTER_TRIGGER A0
#define PIN_PAN_HALL A1
#define PIN_TILT_HALL A2
#define PIN_SLIDER_HALL A3
#define PIN_INPUT_VOLTAGE A6

#define PIN_MS1 11
#define PIN_MS2 10
#define PIN_MS3 9

#define PIN_STEP_SLIDER 7
#define PIN_DIRECTION_SLIDER 4
#define PIN_STEP_TILT 6
#define PIN_DIRECTION_TILT 3
#define PIN_STEP_PAN 5
#define PIN_DIRECTION_PAN 2
#define PIN_ENABLE 8

#define HALF_STEP 2
#define QUARTER_STEP 4
#define EIGHTH_STEP 8
#define SIXTEENTH_STEP 16

#define SLIDER_PULLEY_TEETH 36.0
#define PAN_GEAR_RATIO 8.4705882352941176470588235294118 //144/17 teeth
//Used with the belt driven tilt axis.
//#define TILT_GEAR_RATIO 7.6875 //123/16 teeth
//Used with herringbone gears
#define TILT_GEAR_RATIO 3.047619047619047619047619047619 //64/21 teeth

#define MAX_STRING_LENGTH 10
#define KEYFRAME_ARRAY_LENGTH 35

#define SHUTTER_DELAY 200

#define INSTRUCTION_BYTES_SLIDER_PAN_TILT_SPEED 4
#define INSTRUCTION_STEP_MODE 'm'
#define INSTRUCTION_PAN_DEGREES 'p'
#define INSTRUCTION_TILT_DEGREES 't'
#define INSTRUCTION_ENABLE 'e'
#define INSTRUCTION_SET_PAN_SPEED 's'
#define INSTRUCTION_SET_TILT_SPEED 'S'
#define INSTRUCTION_INVERT_PAN 'i'
#define INSTRUCTION_INVERT_TILT 'I'
#define INSTRUCTION_SET_PAN_HALL_OFFSET 'o'
#define INSTRUCTION_SET_TILT_HALL_OFFSET 'O'
#define INSTRUCTION_SET_HOMING 'H'
#define INSTRUCTION_TRIGGER_SHUTTER 'c'
#define INSTRUCTION_AUTO_HOME 'A'
#define INSTRUCTION_DEBUG_STATUS 'R'
#define INSTRUCTION_EXECUTE_MOVES ';'
#define INSTRUCTION_ADD_POSITION '#'
#define INSTRUCTION_STEP_FORWARD '>'
#define INSTRUCTION_STEP_BACKWARD '<'
#define INSTRUCTION_JUMP_TO_START '['
#define INSTRUCTION_JUMP_TO_END ']'
#define INSTRUCTION_EDIT_ARRAY 'E'
#define INSTRUCTION_ADD_DELAY 'd'
#define INSTRUCTION_EDIT_DELAY 'D'
#define INSTRUCTION_CLEAR_ARRAY 'C'
#define INSTRUCTION_SAVE_TO_EEPROM 'U'
#define INSTRUCTION_PANORAMICLAPSE 'L'
#define INSTRUCTION_ANGLE_BETWEEN_PICTURES 'b'
#define INSTRUCTION_DELAY_BETWEEN_PICTURES 'B'
#define INSTRUCTION_TIMELAPSE 'l'
#define INSTRUCTION_SLIDER_MILLIMETRES 'x'
#define INSTRUCTION_INVERT_SLIDER 'j'
#define INSTRUCTION_SET_SLIDER_SPEED 'X'
#define INSTRUCTION_ORIBIT_POINT '@'
#define INSTRUCTION_CALCULATE_TARGET_POINT 'T'
#define INSTRUCTION_ACCEL_ENABLE 'a'
#define INSTRUCTION_PAN_ACCEL_INCREMENT_DELAY 'q'
#define INSTRUCTION_TILT_ACCEL_INCREMENT_DELAY 'Q'
#define INSTRUCTION_SLIDER_ACCEL_INCREMENT_DELAY 'w'
#define INSTRUCTION_SCALE_SPEED 'W'

#define EEPROM_ADDRESS_HOMING_MODE 0
#define EEPROM_ADDRESS_PAN_MAX_SPEED 17
#define EEPROM_ADDRESS_TILT_MAX_SPEED 21
#define EEPROM_ADDRESS_HALL_PAN_OFFSET 33
#define EEPROM_ADDRESS_HALL_TILT_OFFSET 37
#define EEPROM_ADDRESS_INVERT_PAN 41
#define EEPROM_ADDRESS_INVERT_TILT 42
#define EEPROM_ADDRESS_MODE 43
#define EEPROM_ADDRESS_DEGREES_PER_PICTURE 45
#define EEPROM_ADDRESS_PANORAMICLAPSE_DELAY 49
#define EEPROM_ADDRESS_SLIDER_MAX_SPEED 70
#define EEPROM_ADDRESS_SLIDER_ACCELERATION 74
#define EEPROM_ADDRESS_INVERT_SLIDER 78
#define EEPROM_ADDRESS_ACCELERATION_ENABLE 79
#define EEPROM_ADDRESS_PAN_ACCEL_INCREMENT_DELAY 80
#define EEPROM_ADDRESS_TILT_ACCEL_INCREMENT_DELAY 82
#define EEPROM_ADDRESS_SLIDER_ACCEL_INCREMENT_DELAY 84

#define BLE_DEVICE_NAME "Camera Slider"

#define BLE_GENERAL_INFO_SERVICE_UUID "09E1F127-0E14-43FA-B453-74CC180B2C00"
#define BLE_SERIAL_COMMAND_SERVICE_UUID "1AD18BD9-F649-47B8-87E6-CF9185A53700"

#define BLE_GENERAL_INFO_BLE_API_VERSION_UUID "09E1F127-0E14-43FA-B453-74CC180B2C00"
#define BLE_GENERAL_INFO_SOFTWARE_VERSION_UUID "09E1F127-0E14-43FA-B453-74CC180B2C01"
#define BLE_GENERAL_INFO_DEVICE_NAME_UUID "09E1F127-0E14-43FA-B453-74CC180B2C02"

#define BLE_SERIAL_COMMAND_COMMAND_FROM_MOBILE_DEVICE_UUID "1AD18BD9-F649-47B8-87E6-CF9185A53700"
#define BLE_SERIAL_COMMAND_COMMAND_TO_MOBILE_DEVICE_UUID "1AD18BD9-F649-47B8-87E6-CF9185A53701"

#define VERSION_NUMBER "Version: 3.11.3\n"
#define BLE_API_VERSION "1.0.0"
#define SOFTWARE_VERSION "3.11.3"

#endif